/*
 * common.h
 *
 *  Created on: Apr 21, 2024
 *      Author: veins
 */

#ifndef COMMON_H_
#define COMMON_H_

// Enumeration types tracking the stage of protocol.
enum class CoinAssignmentStage {
    INIT,
    REQUESTED,
    SENT,
    FINISHED,
    FAILED
};

enum class CoinDepositStage {
    INIT,
    REQUESTED,
    SIGNATURE_REQUESTED,
    SIGNATURE_SENT,
    SUBMITTED,
    FINISHED,
    FAILED
};

// Sizes of messages.
#define HEADER_BYTE_SIZE 54
#define COIN_REQUEST_BYTE_SIZE (32 + HEADER_BYTE_SIZE)
#define COIN_ASSIGNMENT_BYTE_SIZE (3263 + HEADER_BYTE_SIZE)
#define COIN_DEPOSIT_BYTE_SIZE (3391 + HEADER_BYTE_SIZE)
#define COIN_DEPOSIT_SIGNATURE_REQUEST_BYTE_SIZE (62 + HEADER_BYTE_SIZE)
#define COIN_DEPOSIT_SIGNATURE_RESPONSE_BYTE_SIZE (230 + HEADER_BYTE_SIZE)
#define COIN_SUBMISSION_BYTE_SIZE (3387 + HEADER_BYTE_SIZE)

// Computation workloads.
// TODO: Should be a model involving latencies and CPU loads.
#define COIN_REQUEST_LATENCY_MEAN 0.0001
#define COIN_REQUEST_LATENCY_STDDEV 0.0001
#define COIN_ASSIGNMENT_LATENCY_MEAN 0.029
#define COIN_ASSIGNMENT_LATENCY_STDDEV 0.002
#define COIN_DEPOSIT_LATENCY_MEAN 0.0001
#define COIN_DEPOSIT_LATENCY_STDDEV 0.0001
#define COIN_DEPOSIT_SIGNATURE_REQUEST_LATENCY_MEAN 0.041
#define COIN_DEPOSIT_SIGNATURE_REQUEST_LATENCY_STDDEV 0.003
#define COIN_DEPOSIT_SIGNATURE_RESPONSE_LATENCY_MEAN 0.0005
#define COIN_DEPOSIT_SIGNATURE_RESPONSE_LATENCY_STDDEV 0.0005
#define COIN_SUBMISSION_LATENCY_MEAN 0.001
#define COIN_SUBMISSION_LATENCY_STDDEV 0.0001

#endif
